---
####### DOCKER #######
- name: Create Folder
  file:
    path: /mnt/volume/docker
    owner: root
    group: root
    state: directory
    mode: 0710

- name: Create mount
  file:
    path: /var/lib/docker
    src: /mnt/volume/docker
    state: link
  when: volumes[inventory_hostname] is defined
