---
####### GRAFANA #######
- name: Create grafana Group
  group:
    name: grafana

- name: Create grafana User
  user:
    name: grafana
    group: grafana

- name: Create Folder
  file:
    path: /mnt/volume/grafana
    owner: grafana
    group: grafana
    state: directory
    mode: 0755

- name: Create mount
  file:
    path: /var/lib/grafana
    src: /mnt/volume/grafana
    state: link
  when: volumes[inventory_hostname] is defined
