---
####### INFLUXDB #######
- name: Create influxdb Group
  group:
    name: influxdb

- name: Create influxdb User
  user:
    name: influxdb
    group: influxdb

- name: Create Folder
  file:
    path: /mnt/volume/influxdb
    owner: influxdb
    group: influxdb
    state: directory
    mode: 0755

- name: Create symlink
  file:
    path: /var/lib/influxdb
    src: /mnt/volume/influxdb
    state: link
  when: volumes[inventory_hostname] is defined
