---
- name: install zfsutils-linux
  apt:
    name: zfsutils-linux
    state: present

- name: install zfs-auto-snapshot
  apt:
    name: zfs-auto-snapshot
    state: present

- name: Format Volume
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.device }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  when: item.fstype != 'zfs'

- name: Mount Volume
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ volumes[inventory_hostname] | list }}"
  when: item.fstype != 'zfs'

- name: Import ZFS zpool
  command: "zpool import -f pool{{ idx }}"
  args:
    creates: "{{ item.mount_point }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  loop_control:
    index_var: idx
  when: item.fstype == 'zfs'
  ignore_errors: yes

- name: Setup ZFS zpool
  command: "zpool create -m {{ item.mount_point }} pool{{ idx }} {{ item.device }}"
  args:
    creates: "{{ item.mount_point }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  loop_control:
    index_var: idx
  when: item.fstype == 'zfs'

- name: Enable ZFS compression
  command: "zfs set compression=zstd pool{{ idx }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  loop_control:
    index_var: idx
  when: item.fstype == 'zfs'

# keep a day of hourly snaps
- name: Update hourly ZFS snapshot retention
  replace:
    path: /etc/cron.hourly/zfs-auto-snapshot
    regexp: '--keep=\d+'
    replace: '--keep=24'

# keep 7 daily snaps
- name: Update daily ZFS snapshot retention
  replace:
    path: /etc/cron.daily/zfs-auto-snapshot
    regexp: '--keep=\d+'
    replace: '--keep=7'

# keep a month of weekly snaps
- name: Update weekly ZFS snapshot retention
  replace:
    path: /etc/cron.weekly/zfs-auto-snapshot
    regexp: '--keep=\d+'
    replace: '--keep=4'

# keep 2 months snaps
- name: Update monthly ZFS snapshot retention
  replace:
    path: /etc/cron.monthly/zfs-auto-snapshot
    regexp: '--keep=\d+'
    replace: '--keep=2'
