---
- name: Create mysql Group
  group:
    name: mysql

- name: Create mysql User
  user:
    name: mysql
    group: mysql

- name: Create Folder
  file:
    path: /mnt/volume/mysql
    owner: mysql
    group: mysql
    state: directory
    mode: 0755

- name: Create symlink
  file:
    path: /var/lib/mysql
    src: /mnt/volume/mysql
    state: link
  when: volumes[inventory_hostname] is defined
