- name: get tool list
  command:
    cmd: python tool_list.py
  delegate_to: "localhost"

- name: install tools
  command:
    cmd: ./roles/usegalaxy_ca.tools/files/install_tools.sh {{ usegalaxy_domain }} {{ GALAXY_ADMIN_API_KEY }}
  delegate_to: "localhost"
