preferences:
  accp:
  omero_account:
    description: Your OMERO instance connection credentials
    inputs:
      - name: username
        label: Username
        type: text
        required: false
      - name: password
        label: Password
        type: password
        required: false
#    description: ACCP (Alliance Cloud Connect Pilot) Settings
#    inputs:
#      - name: pulsar_host
#        label: Pulsar Host
#        type: text
#        required: False
#      - name: pulsar_api_key
#        label: Pulsar API Key
#        type: text
#        required: False
#      - name: pulsar_ram
#        label: Pulsar RAM
#        type: text
#        required: False
#      - name: pulsar_cpu
#        label: Pulsar CPU Cores
#        type: text
#        required: False
