---
- name: Install NFS utils
  apt:
    name:
      - nfs-kernel-server
    state: present

- name: Check the mnt folder exists
  file:
    path: "{{ nfs_mnt_folder }}"
    state: directory

- name: Mount Volume
  ansible.posix.mount:
    path: "{{ nfs_mnt_folder }}"
    src: "{{ nfs_host }}:{{ nfs_host_folder }}"
    fstype: nfs
    state: mounted
