---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m venv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy

# Common variables needed by all hosts
galaxy_user_name: galaxy
galaxy_db_name: galaxy

#domain
usegalaxy_domain: "{{ lookup('env', 'GALAXY_HOSTNAME') }}"
galaxy_subnet: "{{ lookup('env', 'GALAXY_SUBNET') }}"
galaxy_public_page_url: "{{ lookup('env', 'GALAXY_PUBLIC_PAGE_URL') }}"

## CVMFS vars
cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: 10000 #cache size in MB

## Slurm
slurm_config:
  SlurmctldHost: "{{ groups['slurmcontrolservers'][0] }}"
  SelectType: select/cons_res
  SelectTypeParameters: CR_CPU_Memory # Allocate individual cores/memory instead of entire node
slurm_partitions:
  - name: main
    Default: YES
    MaxTime: UNLIMITED
    #Nodes: "{{ groups['slurmexecservers'][0] }}"
    Nodes: ALL
  - name: submit
    Hidden: YES
    State: INACTIVE
    Default: NO
    MaxTime: UNLIMITED
    Nodes: "{{ groups['galaxyservers'][0] }}"
slurm_user:
  group: slurm
  name: slurm

# Galaxy vars that will be reused by Pulsar
galaxy_job_metrics_plugins:
  - type: core
  - type: cpuinfo
  - type: meminfo
  - type: uname
  - type: env
  - type: cgroup
  - type: hostname

# Telegraf
telegraf_agent_package_state: latest

# Configure the output to point to an InfluxDB
# place data in the database "telegraf" which will be created if need be.
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://{{ groups['monitorservers'][0] }}:8086"]
      - database = "telegraf"

# The default plugins, applied to any telegraf-configured host
telegraf_plugins_default:
  - plugin: cpu
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat

# Sentry
# sentry_domain: "sentry.{{ inventory_hostname }}"
sentry_domain: "sentry.jl-galaxy.usegalaxy.ca"
