# Install pip docker package for ansible
pip_install_packages:
  - name: docker
# RabbitMQ
rabbitmq_container:
  name: rabbit_hole
  image: rabbitmq:3.11-management
  hostname: "{{ inventory_hostname }}"

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_config:
  listeners:
    tcp: none
  ssl_listeners:
    default: 5671
  ssl_options:
    verify: verify_peer
    cacertfile: /etc/ssl/certs/fullchain.pem
    certfile: /etc/ssl/certs/cert.pem
    keyfile: /etc/ssl/user/privkey-999:999.pem
    fail_if_no_peer_cert: 'false'
  management_agent:
    disable_metrics_collector: "false"
  management:
    disable_stats: 'false'
  consumer_timeout: 21600000 # 6 hours in milliseconds

rabbitmq_vhosts:
  - /pulsar/pulsar_au

rabbitmq_users:
  - user: admin
    password: "{{ RABBITMQ_ADMIN_PASSWORD }}"
    tags: administrator
    vhost: /
  - user: pulsar_au
    password: "{{ RABBITMQ_PASSWORD_VHOST }}"
    vhost: /pulsar/pulsar_au
