vault_id_secret: "{{ lookup('env', 'VAULT_ID_SECRET') }}"
galaxy_postgres_password: "{{ lookup('env', 'VAULT_POSTGRES_PASSWORD') }}"

# CILogon setup variables
CILOGON_CLIENT_ID: "{{ lookup('env','CILOGON_CLIENT_ID') }}"
CILOGON_CLIENT_SECRET: "{{ lookup('env','CILOGON_CLIENT_SECRET') }}"
CILOGON_REDIRECT_URI: "{{ lookup('env','CILOGON_REDIRECT_URI') }}"
