---
slurm_roles: ["controller", "dbd"]

slurm_database_user: slurm
slurm_database_user_password: "{{ SLURMDB_PASSWORD }}"
slurm_database: "slurm_acct_db"

# patch from AU infra to fix broken slurm role
__slurmdbd_config_default: # overriding this to remove deprecated SlurmctldPidFile (using this key breaks it)
  AuthType: auth/munge
  DbdPort: 6819
  SlurmUser: "{{ __slurm_user_name }}"
  # SlurmctldPidFile: "{{ __slurm_run_dir ~ '/slurmdbd.pid' if __slurm_debian else omit }}"
  LogFile: "{{ __slurm_log_dir ~ '/slurmdbd.log' if __slurm_debian else omit }}"

#Slurmdbd
slurmdbd_config:
  AuthType: auth/munge
  AuthInfo: /var/run/munge/munge.socket.2
  DbdHost: localhost
  DbdPort: 6819
  StorageHost: localhost
  StorageLoc: "{{ slurm_database }}"
  StoragePass: "{{ slurm_database_user_password }}"
  StorageType: accounting_storage/mysql
  StorageUser: "{{ slurm_database_user }}"
  SlurmUser: slurm

#Mariadb for slurm accounting

mariadb_root_pass: "{{ SLURMDB_ROOT_PASSWORD }}"
mariadb_options:
  innodb_buffer_pool_size: 1073741824 #1GB
  innodb_log_file_size: 67108864 #64MB
  innodb_lock_wait_timeout: 900
mariadb_users:
  - name: "{{ slurm_database_user }}"
    password: "{{ slurm_database_user_password }}"
    priv: "{{ slurm_database }}.*:ALL"
mariadb_databases:
  - name: "{{ slurm_database }}"
