# This cron job runs every Monday at 06:00
# It cleans up datasets that have been deleted for more than 14 days
galaxy_pgcleanup_cron_weekday: "1"
galaxy_pgcleanup_cron_hour: "06"
galaxy_pgcleanup_cron_min: "0"
galaxy_pgcleanup_days: 14
# order of action is important!
galaxy_pgcleanup_actions:
  - delete_userless_histories
  - delete_exported_histories
  - purge_deleted_histories
  - purge_deleted_hdas
  - purge_historyless_hdas
  - purge_error_hdas
  - purge_hdas_of_purged_histories
  - delete_datasets
  - purge_datasets
