global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 3.8
  __DATA_FETCH__:
    scheduling:
      reject:
        - pulsar
  toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann/.*:
    cores: 16
    mem: 110
  toolshed.g2.bx.psu.edu/repos/iuc/dada2_assigntaxonomyaddspecies/.*:
    mem: 50
  toolshed.g2.bx.psu.edu/repos/q2d2/qiime2__dada2__denoise_paired/.*:
    mem: 50
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_pca/bio3d_pca/.*:
    mem: 160
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_rmsd/bio3d_rmsd/.*:
    mem: 160
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_rmsf/bio3d_rmsf/.*:
    mem: 160
  toolshed.g2.bx.psu.edu/repos/iuc/spades_biosyntheticspades/spades_biosyntheticspades/.*:
    cores: 10
    mem: 200
  toolshed.g2.bx.psu.edu/repos/nml/metaspades/metaspades/.*:
    cores: 10
    mem: 200
    rules:
      # stubbornly override the shared tpv rule
      - id: tpvdb_metaspades_medium_input_rule
        if: 1 <= input_size < 60
        cores: 10
        mem: 200
  toolshed.g2.bx.psu.edu/repos/iuc/spades_metaplasmidspades/spades_metaplasmidspades/.*:
    cores: 10
    mem: 200
  toolshed.g2.bx.psu.edu/repos/iuc/spades_metaviralspades/spades_metaviralspades/.*:
    cores: 10
    mem: 200
  toolshed.g2.bx.psu.edu/repos/iuc/spades_plasmidspades/spades_plasmidspades/.*:
    cores: 10
    mem: 200
  toolshed.g2.bx.psu.edu/repos/iuc/trinity/trinity/.*:
    cores: 32
    mem: 200
    env:
      _JAVA_OPTIONS: -Xmx{int(mem)}G -Xms1G
  toolshed.g2.bx.psu.edu/repos/nml/spades/spades/.*:
    cores: 20
    mem: 200
  toolshed.g2.bx.psu.edu/repos/iuc/minimap2/minimap2/.*:
    cores: 8
    mem: 200
  .*testing.*:
    cores: 2
    mem: cores * 3.8
    rules:
      - id: admin_only_testing_tool
        if: |
          # Only allow the tool to be executed if the user is an admin
          admin_users = app.config.admin_users
          # last line in block must evaluate to a value - which determines whether the TPV if conditional matches or not
          not user or user.email not in admin_users
        fail: Unauthorized. Only admins can execute this tool.
  toolshed.g2.bx.psu.edu/repos/iuc/kraken2/kraken2/.*:
    mem: 200
  toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/.*:
    cores: min(max(int(input_size * 4), 1), 16)
    mem: min(max(int(input_size * 7), 5.6), 120)

roles:
  training.*:
    scheduling:
      prefer:
        - training

destinations:
  _default_env:
    abstract: true
    env:
      - name: _JAVA_OPTIONS
        value: -Djava.io.tmpdir=$_GALAXY_JOB_TMP_DIR -Xmx{int(mem)}G -Xms256M
      - name: SINGULARITYENV__JAVA_OPTIONS
        value: $_JAVA_OPTIONS
      - execute: ulimit -f 1048576000  # 500GB, our default quota
      - execute: ulimit -u 10000

  slurm-training:
    runner: slurm
    inherits: _default_env
    max_accepted_cores: 32
    max_accepted_mem: 240
    params:
      native_specification: --nodes=1 --ntasks=1 --cpus-per-task={cores} --mem={round(mem*1024)} --time=48:00:00 --partition=training
      singularity_enabled: true
      singularity_volumes: "$galaxy_root:ro,$tool_directory:ro,$working_directory:rw,$job_directory:rw,/mnt/nfs/data/datasets:ro,/mnt/nfs1/data/datasets:ro,/mnt/nfs2/data/datasets:ro,/cvmfs/data.galaxyproject.org:ro"
      tmp_dir: true
    env:
      LC_ALL: C
      SINGULARITY_CACHEDIR: /tmp/singularity
      APPTAINER_TMPDIR: /tmp
    scheduling:
      require:
        - training
  slurm:
    runner: slurm
    inherits: _default_env
    max_accepted_cores: 32
    max_accepted_mem: 1000 # virtually high to catch all, and then downsize to max_mem
    # Clamp resources to what the nodes support.
    max_cores: 32
    max_mem: 220
    params:
      native_specification: --nodes=1 --ntasks=1 --cpus-per-task={cores} --mem={round(mem*1024)} --time=168:00:00 --partition=main #set to main for autumn season
      singularity_enabled: true
      singularity_volumes: "$galaxy_root:ro,$tool_directory:ro,$working_directory:rw,$job_directory:rw,/mnt/nfs/data/datasets:ro,/mnt/nfs1/data/datasets:ro,/mnt/nfs2/data/datasets:ro,/cvmfs/data.galaxyproject.org:ro"
      tmp_dir: true
    env:
      # Ensuring a consistent collation environment is good for reproducibility.
      LC_ALL: C
      # The cache directory holds the docker containers that get converted
      SINGULARITY_CACHEDIR: /tmp/singularity
      # Singularity uses a temporary directory to build the squashfs filesystem
      APPTAINER_TMPDIR: /tmp
    scheduling:
      reject:
        - training
