- name: Create Folder
  file:
    path: /mnt/backup
    owner: postgres
    group: postgres
    state: directory
    mode: 0700

- name: install cargo
  package:
    name: "cargo"
    state: present

- name: git clone backup-rotation
  git:
    repo: git@github.com:laperlej/backup-rotation.git
    dest: ~/backup-rotation

- name: install backup-rotation cli
  command:
    cmd: cargo install --path .
    chdir: ~/backup-rotation

- name: pgpass
  copy:
    content: "{{ groups['dbservers'][0] }}:5432:{{ galaxy_db_name }}:{{ galaxy_user_name }}:{{ galaxy_postgres_password }}"
    dest: /home/postgres/.pgpass
    owner: "postgres"
    group: "postgres"
    mode: "0600"

- name: Cron job for psql backup
  ansible.builtin.cron:
    name: "Backup psql"
    hour: "3"
    minute: "0"
    user: "postgres"
    job: "pg_dump -d {{ galaxy_db_name }} -Fc > /mnt/backup/pg_$(date +\\%Y-\\%m-\\%d_\\%H--\\%M-\\%S).tar"

- name: Cron job for psql backup rotation
  ansible.builtin.cron:
    name: "Rotate psql backups"
    hour: "3"
    minute: "30"
    user: "postgres"
    job: "backup-rotation --format pg_%Y-%m-%d_%H--%M-%S.tar /mnt/backup/pg_*.tar"
