---
- hosts: nfsservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.nfs_server
    - dj-wasabi.telegraf
    - usegalaxy_ca.backup_tsm

- hosts: squidservers
  become: true
  become_user: root
  vars_files:
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsservers.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.squid
    - laperlej.cvmfs
    - dj-wasabi.telegraf

- hosts: slurmcontrolservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["controller"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
  roles:
    - usegalaxy_ca.nfs_client
    - usegalaxy_ca.slurm
    - galaxyproject.repos
    - galaxyproject.slurm
    - dj-wasabi.telegraf

- hosts: slurmexecservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - usegalaxy_ca.nfs_client
    - usegalaxy_eu.apptainer
    - laperlej.cvmfs
    - usegalaxy_ca.slurm
    - galaxyproject.repos
    - galaxyproject.slurm
    - dj-wasabi.telegraf

- hosts: dbservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  pre_tasks:
    - name: install dependencies
      package:
        name: "acl"
      tags:
        - always
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.postgresql
    - galaxyproject.postgresql
    - role: usegalaxy_ca.restart_postgres
      tags:
        - never
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - usegalaxy_ca.gxadmin
    - galaxyproject.gxadmin
    - dj-wasabi.telegraf
    - usegalaxy_ca.backup_pg
    - usegalaxy_ca.backup_tsm

- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - usegalaxy_ca.nfs_client
    - usegalaxy_ca.slurm
    - galaxyproject.repos
    - galaxyproject.slurm
    - usegalaxy_eu.apptainer
    - galaxyproject.tusd
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - usegalaxy_ca.maintenance
    - galaxyproject.nginx
    - laperlej.cvmfs
    - usegalaxy_ca.drmaa
    - role: usegalaxy_ca.restart_galaxy
      become: true
      become_user: root
    - role: usegalaxy_ca.service_account
      become: false
    - dj-wasabi.telegraf

  post_tasks:
    - name: fetch edugain idps the first time
      command: "bash {{ galaxy_root }}/server/cron/fetch-edugain-idps.bash"
      become: true
      become_user: pgalaxy
    - name: set cron jobs
      ansible.builtin.cron:
        name: "cron jobs to adjust allocations group for canadian users"
        minute: "*/5"
        user: pgalaxy
        job: "bash {{ galaxy_root }}/server/cron/set_new_users_allocation_groups.bash"

- hosts: monitorservers
  become: true
  become_user: root
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
    - pip:
        name: [docker, docker-compose]
        tags:
          - always
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - monitor
        - nfs
    - usegalaxy_ca.monitor
    - usegalaxy_ca.docker
    - usegalaxy_ca.influxdb_key
    - usegalaxy_eu.influxdb
    - cloudalchemy.grafana
    - dj-wasabi.telegraf
    - mvdbeek.sentry_selfhosted
    - usegalaxy_ca.backup_influx
    - usegalaxy_ca.backup_tsm
