- hosts: squidservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/cvmfsservers.yml
  roles:
    - usegalaxy_ca.volume
    - galaxyproject.cvmfs
    - dj-wasabi.telegraf

- hosts: slurmexecservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/cvmfsclient.yml
  roles:
    - galaxyproject.cvmfs

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/cvmfsclient.yml
  roles:
    - galaxyproject.cvmfs
