---
- hosts: dbservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: "acl"
      tags:
        - always
  roles:
    - role: galaxyproject.postgresql
      tags:
        - setup
        - postgres
    - role: usegalaxy_ca.restart_postgres
      become: true
      tags:
        - setup
        - never
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
      tags:
        - setup
        - postgres

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: galaxyproject.galaxy
      tags:
        - setup
        - galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
      tags:
        - setup
        - galaxy
    - role: galaxyproject.nginx
      tags:
        - setup
        - proxy
