- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - galaxyproject.tusd
    - role: galaxyproject.galaxy
      galaxy_build_client: false
    - role: usegalaxy_eu.tpv_auto_lint
      become: true
      become_user: "{{ galaxy_user_name }}"
    - role: usegalaxy_ca.client
      become: true
      become_user: "{{ galaxy_privsep_user }}"
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - usegalaxy_ca.maintenance
    - galaxyproject.nginx
    - usegalaxy_ca.drmaa
    - role: usegalaxy_ca.restart_galaxy
      become: true
      become_user: root
    - role: usegalaxy_ca.service_account
      become: false

  post_tasks:
    - name: fetch edugain idps the first time
      command: "bash {{ galaxy_root }}/server/cron/fetch-edugain-idps.bash"
      become: true
      become_user: pgalaxy
    - name: set cron jobs
      ansible.builtin.cron:
        name: "cron jobs to adjust allocations group for canadian users"
        minute: "*/5"
        user: pgalaxy
        job: "bash {{ galaxy_root }}/server/cron/set_new_users_allocation_groups.bash"
