---
- hosts: nfsservers
  become: true
  become_user: root
  vars_files:
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - nfs
        - setup
    - role: usegalaxy_ca.nfs_server
      tags:
        - nfs
        - setup

- hosts: slurmcontrolservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["controller"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup

- hosts: slurmexecservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_eu.apptainer
      tags:
        - cvmfs
        - setup
    - role: galaxyproject.cvmfs
      tags:
        - setup
        - cvmfs
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup

- hosts: dbservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: "acl"
      tags:
        - always
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - setup
        - volume
    - role: galaxyproject.postgresql
      tags:
        - setup
        - postgres
    - role: usegalaxy_ca.restart_postgres
      tags:
        - setup
        - never
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
      tags:
        - setup
        - postgres

- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup
    - role: usegalaxy_eu.apptainer
      tags:
        - cvmfs
        - setup
    - role: galaxyproject.tusd
      tags:
        - tusd
        - setup
    - role: galaxyproject.galaxy
      tags:
        - setup
        - galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
      tags:
        - setup
        - galaxy
    - role: galaxyproject.nginx
      tags:
        - setup
        - proxy
    - role: galaxyproject.cvmfs
      tags:
        - setup
        - cvmfs

  post_tasks:
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
      tags:
        - setup
    - name: galaxy systemd restart
      systemd:
        name: galaxy.target
        state: restarted
      tags:
        - setup
