- hosts: monitorservers
  become: true
  become_user: root
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-pip",
            "python3-venv",
            "python3-setuptools",
            "python3-influxdb",
          ]
      tags:
        - always
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.monitor
    - usegalaxy_ca.docker
    - usegalaxy_ca.influxdb_key
    - role: usegalaxy_eu.influxdb
      vars:
        ansible_distribution_release: "stable"
    - cloudalchemy.grafana
    - laperlej.sentry_selfhosted
    - usegalaxy_ca.backup_influx
  post_tasks:
    - name: Configure 30-day retention policy on InfluxDB
      community.general.influxdb_retention_policy:
        database: "telegraf"
        policy_name: 'autogen'
        duration: "{{ influxdb_retention_duration }}"
        replication: 1
        default: true
        hostname: "127.0.0.1"
        port: 8086
        state: present

- hosts: all
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  roles:
    - dj-wasabi.telegraf
