- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: galaxyproject.galaxy
      galaxy_build_client: false
    - role: usegalaxy_ca.patch
      become: true
      become_user: "{{ galaxy_privsep_user }}"
    - role: galaxyproject.galaxy
