- hosts: rabbitmqservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  pre_tasks:
    - name: Override nginx and certbot vars
      set_fact:
        certbot_post_renewal: |
          docker restart rabbit_hole || true
        certbot_domains:
          - "mq.{{ usegalaxy_domain }}"
        nginx_servers:
          - rabbitmq
        nginx_ssl_servers: []
  roles:
    - usegalaxy_eu.certbot
    - geerlingguy.docker
    - usegalaxy_eu.rabbitmqserver
