- hosts: rabbitmqservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  pre_tasks:
    - name: Add cron job for fetching SSL certs
      cron:
        name: Fetch SSL cert files from Galaxy
        job: "rsync -a --delete {{ groups['galaxyservers'][0] }}:{{ item.value }} {{ item.value }}"
        minute: "{{ certbot_auto_renew_minute }}"
        hour: "{{ certbot_auto_renew_hour }}"
        user: "{{ certbot_auto_renew_user }}"
      loop: "{{ rabbitmq_ssl | dict2items }}"
  roles:
    - geerlingguy.docker
    - usegalaxy_eu.rabbitmqserver
