- hosts: rabbitmqservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  roles:
    - geerlingguy.docker
    - usegalaxy_eu.rabbitmqserver
