- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/slurm.yml
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - galaxyproject.galaxy

- hosts: monitorservers
  become: true
  become_user: root
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-pip",
            "python3-venv",
            "python3-setuptools",
          ]
    - copy:
        src: "files/monitor/requirements.txt"
        dest: "~/requirements.txt"
    - pip:
        requirements: "~/requirements.txt"
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.docker
    - laperlej.sentry_selfhosted
