- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/slurm.yml
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - galaxyproject.galaxy

- hosts: monitorservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.docker
    - mvdbeek.sentry_selfhosted
