- hosts: all
  become: true
  become_user: root
  tasks:
    apt:
      name:
        - openssh-server
        - openssh-client
      update_cache: yes
      only_upgrade: yes
      state: latest
    systemd:
      name: sshd
      state: restarted
