- hosts: tusdservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  vars:
    tusd_instances:
      - name: uploads
        user: "{{ galaxy_user.name }}"
        group: "{{ galaxy_group.name }}"
        args:
          - "-port={{ galaxy_tusd_port }}"
          - "-base-path={{ tusd_location }}"
          - "-upload-dir={{ galaxy_tus_upload_store }}"
          - "-hooks-http=https://{{ usegalaxy_domain }}/api/upload/hooks"
          - -hooks-http-forward-headers=X-Api-Key,Cookie
          - -behind-proxy
  roles:
    - galaxyproject.tusd
