#!/usr/bin/env python3
"""
This CLI is used to run common ansible recipes
 
view the help for more information

./usegalaxy.py -h
"""
import argparse
from cli.ansible import Ansible
from cli.dependencies import DependencyManager

"""
Parse args and run the appropriate function
"""
def main():
    parser = ArgParser()
    parser.run()

"""
ArgParser class

Attributes:
    parser: The argparse parser
"""
class ArgParser():
    def __init__(self):
        self.parser = argparse.ArgumentParser(
            prog="UseGalaxyCLI",
            description="Used to run commmon ansible recipes")
        subparsers = self.parser.add_subparsers(help='sub-command help')

        for playbook in ["all", "slurm", "cvmfs", "sentry", "nginx", "backup", "tools"]:
            setup_command = subparsers.add_parser(playbook, help="setup %s" % playbook)
            setup_command.set_defaults(func=lambda: run("%s.yml" % playbook))

        setup_command = subparsers.add_parser('requirements', help="download all requirements")
        setup_command.set_defaults(func=requirements)



    def run(self) -> None:
        args = self.parser.parse_args()
        if not hasattr(args, "func"):
            self.parser.print_help()
            exit(1)
        args.func(args)


"""
Run an ansible playbook
"""
def run(playbook_path: str):
    ansible = Ansible()
    depManager = DependencyManager()

    depManager.verify_all()
    ansible.set_yaml(playbook_path)

    ansible.run()

"""
run the ansible requirements
"""
def requirements(args):
    ansible = Ansible()
    depManager = DependencyManager()

    depManager.update_venv()
    depManager.verify_all()

    ansible.requirements()


if __name__ == "__main__":
    main()
