---
- hosts: nfsservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.nfs_server
    - usegalaxy_ca.logrotate

- hosts: squidservers
  become: true
  become_user: root
  vars_files:
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsservers.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.squid
    - laperlej.cvmfs

- hosts: slurmcontrolservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["controller"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
  roles:
    - usegalaxy_ca.nfs_client

- hosts: slurmexecservers
  become: true
  become_user: root
  vars:
    slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - usegalaxy_ca.nfs_client
    - laperlej.cvmfs

- hosts: dbservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  pre_tasks:
    - name: install dependencies
      package:
        name: "acl"
      tags:
        - always
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.logrotate

- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - usegalaxy_ca.nfs_client
    - laperlej.cvmfs
    - usegalaxy_ca.logrotate

- hosts: monitorservers
  become: true
  become_user: root
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-pip",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  roles:
    - usegalaxy_ca.volume
    - usegalaxy_ca.logrotate

- hosts: tusdservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/galaxyservers.yml
  roles:
    - usegalaxy_ca.nfs_client

- hosts: pulsarservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/cvmfsclient.yml
  roles:
    - laperlej.cvmfs
