- name: Create Folder
  file:
    path: /mnt/volume/backup
    owner: influxdb
    group: influxdb
    state: directory
    mode: 0700

- name: Create mount
  file:
    path: /mnt/backup
    src: /mnt/volume/backup
    state: link
  when: volumes[inventory_hostname] is defined

- name: install cargo
  package:
    name: "cargo"
    state: present

- name: install backup-rotation cli
  command:
    cmd: cargo install --git https://github.com/laperlej/backup-rotation.git
  become_user: influxdb
  become: true

- name: Cron job for influxdb backup
  ansible.builtin.cron:
    name: "Backup influxdb"
    hour: "3"
    minute: "0"
    user: "influxdb"
    job: "influxd backup -portable /mnt/backup/influx_$(date +\\%Y-\\%m-\\%d_\\%H-\\%M-\\%S)"

- name: Cron job for influxdb backup rotation
  ansible.builtin.cron:
    name: "Rotate influxdb backups"
    hour: "3"
    minute: "30"
    user: "influxdb"
    job: "~/.cargo/bin/backup-rotation --format influx_\\%Y-\\%m-\\%d_\\%H-\\%M-\\%S /mnt/backup/influx_*"
